### ISSUE TITLE
Support for updating images?

### ISSUE THREAD

**Issue by gavinbarron** [petegrimsdale/aks_testing_fwk#11]
Thanks for this tool. 

Currently the only mechanism available to update an image is to manually build and push to the acr instance and then update the running applications. 
Do you think that the ability to update jmeter images and update the application containers on the fly would be a useful option to expose to users as another script option?

**Comment by petegrimsdale** [comment]
Hi Gavin - this is something we have not looked at, but is a good suggestion.  We see the test framework usually as a short-lived implementation which is removed when testing is complete but image update would be something we could consider adding.
