### ISSUE TITLE
Support for JMeter Plugin Manager 

### ISSUE THREAD

**Issue by gavinbarron** [petegrimsdale/aks_testing_fwk#12]
Should the base jmeter images have PluginManager baked in?

I think that providing documentation on how to set up your test rig with custom plugins could be useful at a minimum

Our JMeter tests make use of the Concurrency Thread Group plugin. In order to execute these tests it's necessary to update the Dockerfiles for both of the jmeter images to load the Plugin Manager and the plugin(s) that are needed by the tests.

Going down this path would also unlock using the Azure Application Insights Backend Listener as an alternative to the Grafana reporting using the influx listener.

**Comment by petegrimsdale** [comment]
Adding the plugins is something we plan to do - we started with keeping the images as lightweight as possible but as we have developed the Azure Application Insights Backend Listener in conjunction with the testing framework work this is something we will be adding.  The simple solution at this time would be to amend the Dockerfile used to build the images to add the required extension jar files to the /lib/ext folder when the images are created but we'll look at adding support for the plugin manager in the next iteration

**Comment by gavinbarron** [comment]
Would you like a PR and some docs on this?

I made a working example in my tinkering.

**Comment by petegrimsdale** [comment]
That would be great but I have a PR almost ready to include - this will allow you to option call either the install script but more likely an update script which will push an updated version of the master and slave images to the acr which can then be updated on the deployment.   The new default images will include plugin manager support and the azure backend listener plugin by default

**Comment by petegrimsdale** [comment]
@gavinbarron.  The plan we have at the moment is to provide an update.sh script in the install directory that will take a single parameter - the resource group containing the acr in use.   It will build the master and slave Dockerfiles and push these, so is reliant on updates to those files - for which I will have some docs.  Do you think it would make sense to then force these images to be deployed by scaling the current replica's to 0 and back up or leave that to the user with instructions ?

**Comment by gavinbarron** [comment]
I'd probably allow for an optional --update-replicas flag to trigger that behavior

**Comment by petegrimsdale** [comment]
@gavinbarron - we now have a branch that allows update of images and as a result update of the deployed replicas to allow changes to be made to the images being used.
