### ISSUE TITLE
Errors in docker images

### ISSUE THREAD

**Issue by guilhermejp8** [petegrimsdale/aks_testing_fwk#13]
Hi I ran the script, but my pods are in error.
I tried to run the dockerfile files locally and they still don't work

![image](https://user-images.githubusercontent.com/26007518/96258948-2fb60800-0f93-11eb-9465-2d978352cbb4.png)

I believe the error is in the image of the docker, because it does not run locally

**Comment by petegrimsdale** [comment]
@guilhermejp8 - I'll check this out as we have not seen this issue - can you paste the contents of the installer log file please so I can verify the images have been pushed to the container registry correctly in your deployment. You should see something like:

Successfully built 2a4a5e0009b0
Successfully tagged testframeworkacrbb054.azurecr.io/testframework/jmetermaster:latest
2020/08/24 11:16:45 Successfully executed container: build
2020/08/24 11:16:45 Executing step ID: push. Timeout(sec): 3600, Working directory: '', Network: ''
2020/08/24 11:16:45 Pushing image: testframeworkacrbb054.azurecr.io/testframework/jmetermaster:latest, attempt 1
The push refers to repository [testframeworkacrbb054.azurecr.io/testframework/jmetermaster]
c8b4dfc153ce: Preparing
7305d94e5c83: Preparing
27fb13b15a0c: Preparing
20099cc3e8de: Preparing
ed7152ed4cbd: Preparing
95c20fa5728d: Preparing
d0f104dc0a1f: Preparing
95c20fa5728d: Waiting
d0f104dc0a1f: Waiting
c8b4dfc153ce: Pushed
ed7152ed4cbd: Pushed
27fb13b15a0c: Pushed
7305d94e5c83: Pushed
95c20fa5728d: Pushed
20099cc3e8de: Pushed
d0f104dc0a1f: Pushed
latest: digest: sha256:ad7feef70041d0f1f3b60fe06f63a8a3dbb7320ec3b64583a543f01a83819e15 size: 1791
2020/08/24 11:17:23 Successfully pushed image: testframeworkacrbb054.azurecr.io/testframework/jmetermaster:latest
2020/08/24 11:17:23 Step ID: build marked as successful (elapsed time in seconds: 42.773743)
2020/08/24 11:17:23 Populating digests for step ID: build...
2020/08/24 11:17:25 Successfully populated digests for step ID: build
2020/08/24 11:17:25 Step ID: push marked as successful (elapsed time in seconds: 37.708085)
2020/08/24 11:17:25 The following dependencies were found:
2020/08/24 11:17:25 
- image:
    registry: testframeworkacrbb054.azurecr.io
    repository: testframework/jmetermaster
    tag: latest
    digest: sha256:ad7feef70041d0f1f3b60fe06f63a8a3dbb7320ec3b64583a543f01a83819e15
  runtime-dependency:
    registry: registry.hub.docker.com
    repository: library/openjdk
    tag: 8-jdk-slim
    digest: sha256:18de8cd753c0a0da5e9e55499642d8573a359b1f28ba291fab82020559c52cbe
  git: {}

Run ID: cb1 was successful after 1m39s
**INFO:jmeter master container completed....**

**Comment by petegrimsdale** [comment]
Dockerfile build correctly locally - I have just verified the master Dockerfile
Removing intermediate container 80a1c2ce7478
 ---> 926ffb3af381
Successfully built 926ffb3af381
Successfully tagged testfwk:latest

**Comment by guilhermejp8** [comment]
Sorry, friend . I found my mistake, my subscription is extremely blocked by the company and with that the service principal does not work. AKS does not have access to the container registry, my solution was to do it inside AKS. Thanks for listening.

`      imagePullSecrets:
        - name: acr-secret`
