### ISSUE TITLE
InfluxDB Error in dashboard for Error Rate % - HTTP Request

### ISSUE THREAD

**Issue by mhackermsft** [petegrimsdale/aks_testing_fwk#6]
![Capture](https://user-images.githubusercontent.com/61195478/75904717-b6a5de00-5e11-11ea-97aa-20ecbcebee83.PNG)

Error is shown for Error Rate% - HTTP Request widget on the dashboard.  This is a clean install of the solution completed today.

**Comment by petegrimsdale** [comment]
@mhackermsft - there is an error in the query behind that tile which I will address in an upcoming version - in the short term you can edit the query and replace the current query with:

SELECT sum("countError") / sum("count")  FROM "$measurement_name" WHERE "transaction" =~ /^$transaction$/ AND "application" =~ /^$application$/ AND $timeFilter
