### ISSUE TITLE
Setup Issue

### ISSUE THREAD

**Issue by nreddipalle** [petegrimsdale/aks_testing_fwk#7]
I finished setting this up but having these issues so far..
1. Reporting pod is not coming online.. 
**reporting-69974c66c4-4mlc6
Pending
0
12 hours
0/4 nodes are available: 1 node(s) had volume node affinity conflict, 3 Insufficient cpu.**

Trying to run starttest.sh from my local (Windows 10 using Git BASH) and I am getting the below error at this step.. 
## Echo Starting Jmeter load test
kubectl --namespace jmeter exec -ti $master_pod -- /bin/bash /load_test "$test_name" 

**$ kubectl --namespace jmeter exec -it $master_pod -- /bin/bash
Unable to use a TTY - input is not a terminal or the right kind of file
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/bash\": stat C:/Program Files/Git/usr/bin/bash: no such file or directory": unknown
command terminated with exit code 126**

Trying to execute the command directly on the container showing me permission denied error...
![image](https://user-images.githubusercontent.com/28302399/80246766-f7b0b680-863a-11ea-9bfa-5a0d49c25630.png)

Any help regarding this is much appreciated..

Thanks

**Comment by petegrimsdale** [comment]
Hi
Can you send me the your log file from the directory you started the install from...it looks like the node taint failed.  What version of the azure cli are you running

Thanks
Pete

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nreddipalle** [comment]
I did not enable the logging.. I split your install.sh script into multiple scripts and running and as per the UI log it says it succeeded.. 
![image](https://user-images.githubusercontent.com/28302399/80252388-2cc20680-8645-11ea-994f-df39ff3ec352.png)

**Comment by petegrimsdale** [comment]
Ok..the taint of the node should allow the reporting pod to be allocated to that node and the master and slave pods should land on the other node.

I've run this multiple times as have the rest of the team from WSL with min 2.0.86 of az cli without issues so I need so more details

Can you run kubectl get pods -o wide to see where the pods are

Also check the deploy templates have been updated to deploy yml files correctly

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nreddipalle** [comment]
Here is the info: 
![image](https://user-images.githubusercontent.com/28302399/80255141-59c4e800-864a-11ea-89f7-14ec3fbe2141.png)
Here are the generated yaml files..
[reporter.yaml.txt](https://github.com/petegrimsdale/aks_testing_fwk/files/4531419/reporter.yaml.txt)
[jmaster.yaml.txt](https://github.com/petegrimsdale/aks_testing_fwk/files/4531420/jmaster.yaml.txt)
[jslave.yaml.txt](https://github.com/petegrimsdale/aks_testing_fwk/files/4531421/jslave.yaml.txt)
The only difference is that instead of setting up new AKS, I am using existing AKS and seperate namespace for this setup..

**Comment by nreddipalle** [comment]
oh.. my az cli is 2.0.76.. maybe thats the problem.. shall I upgrade and run the setup again.. 
![image](https://user-images.githubusercontent.com/28302399/80255552-28005100-864b-11ea-8f69-9f361a7a55b2.png)

**Comment by petegrimsdale** [comment]
There were certainly issues with versions lower than 2.0.83 if I recall correctly.  There is a minimum required version in the readme.  You may also need to look at the kubectl commands if you are not using the default namespace

Peter

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nreddipalle** [comment]
Ok. I am going to upgrade and recreate the reporting node pool.. Yes I modified kubectl commands accordingly to accommodate namespace changes..

# apply the yaml with the substituted value
echo "INFO:Creating Reporting deployment...."
kubectl --namespace jmeter apply -f ../deploy/azure-premium.yaml
kubectl --namespace jmeter apply -f ../deploy/influxdb_svc.yaml
kubectl --namespace jmeter apply -f ../deploy/jmeter_influx_configmap.yaml
kubectl --namespace jmeter apply -f ../deploy/reporter.yaml
echo "INFO:Reporting deployment complete...."
echo "INFO:Creating Jmeter Slaves.."
kubectl --namespace jmeter apply -f ../deploy/jslaves_svc.yaml
kubectl --namespace jmeter apply -f ../deploy/jslave.yaml
echo "INFO:Jmeter slave deployment complete...."

echo "INFO:Creating Jmeter Master"
kubectl --namespace jmeter apply -f ../deploy/jmeter-master-configmap.yaml
kubectl --namespace jmeter apply -f ../deploy/jmaster.yaml
echo "INFO: Jmeter Master deployment complete...."

Is that the same reason sample tests could not run?? I am trying to run the simple.jmx both from my machine and from jenkins master directly but could not succeed.. you can see the error I am facing in my first post..

**Comment by petegrimsdale** [comment]
The command i can see you are running outside the start sh script will mean you need to provide $masterpod

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nreddipalle** [comment]
Yes. I am fetching the master_pod variable before running this command.. 

kubectl --namespace jmeter exec -ti $master_pod -- /bin/bash /load_test "$test_name"

**$ kubectl --namespace jmeter exec -it $master_pod -- /bin/bash
Unable to use a TTY - input is not a terminal or the right kind of file
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: "C:/Program Files/Git/usr/bin/bash": stat C:/Program Files/Git/usr/bin/bash: no such file or directory": unknown
command terminated with exit code 126**

But looks like this issue is something to do with windows 10 and git bash which I am using now..

As an alternative, I tried to run the command on master_pod directly via kubertenes dashboard UI but keep getting permission denied error 
![image](https://user-images.githubusercontent.com/28302399/80258638-b972c180-8651-11ea-973c-f3cecacb5bb6.png)

**Comment by petegrimsdale** [comment]
If you have wsl installed try running from there


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by nreddipalle** [comment]
I will install, try and update. Thanks

**Comment by nreddipalle** [comment]
@petegrimsdale I redeployed it again completely.. the sample test running fine now.. 
But reporting node failed to come up still.. seeing this error on the dashboard..
**reporting
-
0 / 1
19 minutes
0/4 nodes are available: 1 node(s) had volume node affinity conflict, 3 Insufficient cpu.**

**Comment by nreddipalle** [comment]
Quick update: I removed the resources limits from yaml file and it worked fine now.. Any downside if I deploy without resource limits??

**Comment by petegrimsdale** [comment]
Hi,
Yes – the nodepool for the reporting node should have been created with a larger node size to handle the reporting requirements – that is why the taint is in place and the corresponding resource limits.  I would check the node you have deployed for reporting is in fact a D8S_v3 as per this line in the install script

az aks nodepool add --cluster-name $aksName -g $resourceGroup --name reporterpool --node-count 1 --node-vm-size Standard_D8s_v3

You may find the node is too small to handle the reporting requirements for Influx and grafana
